/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  farm_account: () => import("@/views/farm/account/index.vue"),
  farm_activity: () => import("@/views/farm/activity/index.vue"),
  farm_analytics: () => import("@/views/farm/analytics/index.vue"),
  farm_dashboard: () => import("@/views/farm/dashboard/index.vue"),
  farm_friends: () => import("@/views/farm/friends/index.vue"),
  "farm_game-config": () => import("@/views/farm/game-config/index.vue"),
  "farm_game-mall": () => import("@/views/farm/game-mall/index.vue"),
  "farm_mystery-shop": () => import("@/views/farm/mystery-shop/index.vue"),
  farm_personal: () => import("@/views/farm/personal/index.vue"),
  farm_settings: () => import("@/views/farm/settings/index.vue"),
  home: () => import("@/views/home/index.vue"),
  system_admin: () => import("@/views/system/admin/index.vue"),
};
