/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'farm',
    path: '/farm',
    component: 'layout.base',
    meta: {
      title: 'farm',
      i18nKey: 'route.farm'
    },
    children: [
      {
        name: 'farm_account',
        path: '/farm/account',
        component: 'view.farm_account',
        meta: {
          title: 'farm_account',
          i18nKey: 'route.farm_account'
        }
      },
      {
        name: 'farm_activity',
        path: '/farm/activity',
        component: 'view.farm_activity',
        meta: {
          title: 'farm_activity',
          i18nKey: 'route.farm_activity'
        }
      },
      {
        name: 'farm_analytics',
        path: '/farm/analytics',
        component: 'view.farm_analytics',
        meta: {
          title: 'farm_analytics',
          i18nKey: 'route.farm_analytics'
        }
      },
      {
        name: 'farm_card',
        path: '/farm/card',
        component: 'view.farm_card',
        meta: {
          title: 'farm_card',
          i18nKey: 'route.farm_card'
        }
      },
      {
        name: 'farm_dashboard',
        path: '/farm/dashboard',
        component: 'view.farm_dashboard',
        meta: {
          title: 'farm_dashboard',
          i18nKey: 'route.farm_dashboard',
          hideInMenu: true
        }
      },
      {
        name: 'farm_friends',
        path: '/farm/friends',
        component: 'view.farm_friends',
        meta: {
          title: 'farm_friends',
          i18nKey: 'route.farm_friends'
        }
      },
      {
        name: 'farm_game-config',
        path: '/farm/game-config',
        component: 'view.farm_game-config',
        meta: {
          title: 'farm_game-config',
          i18nKey: 'route.farm_game-config'
        }
      },
      {
        name: 'farm_personal',
        path: '/farm/personal',
        component: 'view.farm_personal',
        meta: {
          title: 'farm_personal',
          i18nKey: 'route.farm_personal'
        }
      },
      {
        name: 'farm_settings',
        path: '/farm/settings',
        component: 'view.farm_settings',
        meta: {
          title: 'farm_settings',
          i18nKey: 'route.farm_settings'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      constant: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_admin',
        path: '/system/admin',
        component: 'view.system_admin',
        meta: {
          title: 'system_admin',
          i18nKey: 'route.system_admin'
        }
      },
      {
        name: 'system_attachment',
        path: '/system/attachment',
        component: 'view.system_attachment',
        meta: {
          title: 'system_attachment',
          i18nKey: 'route.system_attachment'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_permission',
        path: '/system/permission',
        component: 'view.system_permission',
        meta: {
          title: 'system_permission',
          i18nKey: 'route.system_permission'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      }
    ]
  }
];
